// <auto-generated />
using System;
using Demo.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Demo.Migrations
{
    [DbContext(typeof(DemoDbContext))]
    [Migration("20201229060408_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Demo.Company", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Created = new DateTime(2020, 12, 29, 11, 34, 7, 848, DateTimeKind.Local).AddTicks(8229),
                            name = "Company1"
                        });
                });

            modelBuilder.Entity("Demo.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("production")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            id = 1,
                            CompanyId = 1,
                            Created = new DateTime(2020, 12, 29, 11, 34, 7, 851, DateTimeKind.Local).AddTicks(2863),
                            name = "product 1",
                            production = new DateTime(2020, 12, 29, 11, 34, 7, 851, DateTimeKind.Local).AddTicks(3491)
                        },
                        new
                        {
                            id = 2,
                            CompanyId = 1,
                            Created = new DateTime(2020, 12, 29, 11, 34, 7, 851, DateTimeKind.Local).AddTicks(4608),
                            name = "product 2",
                            production = new DateTime(2020, 12, 29, 11, 34, 7, 851, DateTimeKind.Local).AddTicks(4617)
                        });
                });

            modelBuilder.Entity("Demo.Product", b =>
                {
                    b.HasOne("Demo.Company", null)
                        .WithMany("Products")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Demo.Company", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
